import path from 'path'
import { defineConfig } from 'vite'
import vuePlugin from '@vitejs/plugin-vue'

module.exports = defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'wc-valtech-ui',
      formats: ['es'], // adding 'umd' requires globals set to every external module
      fileName: (format) => `wc-valtech-ui.${format}.js`,
    },
    // sourcemap: true,
    // minify: true,
    rollupOptions: {
      // external modules won't be bundled into your library
      // external: ['vue'], // not every external has a global
      output: {
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === 'style.css') {
            return 'wc-valtech-ui.css'
          }
          
          return assetInfo.name
        },
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        // globals: {
        //   vue: 'Vue',
        // },
      },
    },
    // Retain the types folder generated by tsc
    emptyOutDir: false,
  },
  plugins: [
    // Allow the processing of SFC
    vuePlugin(),
  ],
  // resolve: {
  //   dedupe: ['vue'],
  // },
});
